//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public Nullable<long> TempleteId { get; set; }
        public long Id { get; set; }
        public string Title { get; set; }
        public string TitleDisp { get; set; }
        public string TitleImg { get; set; }
        public string TitleImgDisp { get; set; }
        public string CreateDate { get; set; }
        public string Tag { get; set; }
        public byte[] Content { get; set; }
        public string LastEdit { get; set; }
        public string LastEditDate { get; set; }
        public Nullable<long> DeleteFlag { get; set; }
        public Nullable<long> HasMusic { get; set; }
        public string MusicList { get; set; }
        public long IsPublish { get; set; }
        public string ExtScript { get; set; }
    }
}
