//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string TitleDisp { get; set; }
        public string TitleImg { get; set; }
        public string TitleImgDisp { get; set; }
        public string CreateDate { get; set; }
        public string Tag { get; set; }
        public byte[] Content { get; set; }
        public string LastEdit { get; set; }
        public string LastEditDate { get; set; }
        public Nullable<long> DeleteFlag { get; set; }
        public Nullable<long> HasMusic { get; set; }
        public string MusicList { get; set; }
        public long IsPublish { get; set; }
        public string ExtScript { get; set; }
    }
}
