//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templete
    {
        public string DispImg { get; set; }
        public long Id { get; set; }
        public string TempleteName { get; set; }
        public byte[] TempleteContent { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
    }
}
