//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templete
    {
        public long Id { get; set; }
        public string TempleteName { get; set; }
        public byte[] TempleteContent { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
    }
}
